### ISSUE TITLE
[BUG] Player not starting because of LoginWindow calling to early

### ISSUE THREAD

**Issue by kanishkyadav** [osu-player/osuplayer#118]
not opening

**Comment by Founntain** [comment]
Please provide some info, we can't help you without any info. If the player doesn't start, then it might be a reason, that the player crashes. So if this is the case you should have a crashlog inside the logs folder, please share the latest log folder.

We need some information otherwise we can't help you!

**Comment by Founntain** [comment]
The reason why the player crashes (doesn't open) is because the Player tries to open the Login Window to soon, which isn't possible when the MainWindow (parent) isn't called yet. I made a fix soon and it will be merged soon
